### PR TITLE
Add CTRL+A to almost every line editor, and improve some character selector functionality

### PR DESCRIPTION
**Pull request by kristomu**
This PR adds the ability to use CTRL+A to call up a character selector on just about every line editor so that users can add extended characters to board titles and similar.

For restricted line editors (numbers-only or filenames), the selector grays out characters that aren't allowed and keeps them from being selected. As a side effect, this fixes a very minor bug where non-digits like { and } could be entered into numerical fields (although they would be erased upon pressing enter).

In addition, the user can jump to a desired region of the character map by pressing a literal key; this will recenter the selector on that key. 

As part of the added functionality, I implemented functions to copy from video memory/buffers to text blocks and back, to restore the screen after the selector is called. I've tested this on SDL but not on DOS.

### CODE REVIEW

**Comment by kristomu** [comment]
I haven't added any mention of this new functionality to the docs; I'm not sure where to put it.

~~I also have to allow character 0 to be chosen for every instance that's not a string (e.g. when choosing a #CHAR value, text tile character, or object appearance). I'll do it with a flag, just haven't got to it yet.~~ Done.

**Comment by cknave** [comment]
These are some really nice improvements for the line editor and character selector!

Possible way to not need to modify all the display drivers: I think everything that calls `line_editor` already knows how to redraw itself. If we passed the redraw function as an argument to `line_editor`, then it could call it after `charselect` returns.

None of those redraw functions have the same signature, but we could also pass a void pointer for context.

Something like:

```c
int line_editor(int x, int y, ...,
/* new args: */ void (*redraw_fn)(void *), void *redraw_ctx)
{
    ...
    charselect(...);
    redraw_fn(redraw_ctx);
    ...
}
```

Then the "generic" redraw functions look something like:
```c
void redraw_board(void *context) {
    keveditor *editor = (keveditor *)context;
    drawscreen(editor);
}   

/* my kingdom for a lambda function */
struct redraw_world_info_ctx {
    keveditor *editor;
    ZZTWorld *world;
}
void redraw_world_info(void *context) {
    struct redraw_world_info_ctx *ctx = (struct redraw_world_info_ctx *)context;
    drawworldinfo(ctx->world, ctx->editor);
}

struct redraw_board_info_ctx {
    displaymethod *mydisplay;
    dialog *dia;
}
void redraw_board_info(void *context) {
    struct redraw_board_info_ctx *ctx = (struct redraw_board_info_ctx *)context
    dialogDraw(ctx->mydisplay, *ctx->dia);
}
```

And you invoke `line_editor` with whatever the appropriate one is for the current context, e.g.:

```c
struct redraw_world_info_ctx redraw_ctx = {myeditor, myworld};
line_editor(x, y, ..., redraw_world_info, &redraw_ctx);
```

lmk what you think. I can probably also take a crack at this some time this week.

**Comment by kristomu** [comment]
I'd think a benefit of the current solution is that everything is hidden from the higher level functionality. The callers of line_edit don't have to care about their own context, because line_edit does it all for them. So I think it would be more maintainable once the initial hurdle is over. I'd just have to find out if it works in DOS.

**Comment by kristomu** [comment]
I just did a test compile on DOS with the following hacky invocation (djgpp wasn't playing nice with ld):

`./djgcc -DPACKAGE_VERSION="\"0.00\"" -DDATAPATH="\".\"" -DDOS -Isrc -Isrc/dialogs src/dialogs/*.c src/display/*dos.c src/display/casing.c src/display/charset.c src/display/display.c src/display/palette.c src/display/textblock.c src/help/*.c src/kevedit/*.c src/libzzt2/board.c src/libzzt2/file.c src/libzzt2/params.c src/libzzt2/strtools.c src/libzzt2/tiles.c src/libzzt2/world.c src/libzzt2/zztoop.c src/structures/*.c src/synth/notes.c src/synth/pcspeaker.c src/synth/zzm.c src/texteditor/[defghijklmnopqrsuvwxyz]*c src/texteditor/texteditor.c src/themes/*/*.c src/zlaunch/zlaunch.c -O2 -oqnd_dos/kevedit.exe`

The resulting DOS executable worked with no problem, so it looks like I got the DOS display code right.

**Comment by cknave** [comment]
Great! I confirmed it's working on a real (if anachronistic) PC running FreeDOS.

You should be able to build the DOS version the same way the CI does if you have python and docker installed:

```
cd inst
./build.py dos
```

**Comment by kristomu** [comment]
FYI: build.py uses `#!/usr/bin/env python` assuming Python 2, which leads to an error on my distro where "python" is Python 3. Would changing it to "python2" work?

**Comment by cknave** [comment]
All the currently supported python versions should work (3.8 to 3.12).

I'd have hoped that distros would point `python` at something that wasn't EOL'd 4 years ago at this point :disappointed:

**Comment by kristomu** [comment]
Oops, got the Python thing the wrong way around. It's actually my distro's fault. Thanks :-)

**Pull request merged**
